import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion"

const faqs = [
  {
    question: "How long does it take to set up Revenue Boost?",
    answer:
      "You can get started in under 5 minutes! Simply install the app from the Shopify App Store, choose a template, customize it to match your brand, and you're ready to go. No coding required.",
  },
  {
    question: "Will popups slow down my website?",
    answer:
      "Absolutely not. Our entire script is under 25KB gzipped — that's smaller than most images on your site. It loads asynchronously and won't affect your page load times, Core Web Vitals, or SEO rankings. Performance is a priority, not an afterthought.",
  },
  {
    question: "Will Revenue Boost work with my theme?",
    answer:
      "Yes, Revenue Boost is compatible with ALL Shopify themes — free, paid, or custom. We use Shadow DOM technology which means our popups render in complete isolation from your theme's CSS. There's zero risk of style conflicts, broken layouts, or visual glitches. It just works.",
  },
  {
    question: "How does the targeting work?",
    answer:
      "Revenue Boost offers powerful targeting options: target by device type (mobile/desktop), customer segments (VIPs, first-time buyers, repeat customers), new vs returning visitors, geographic location, specific pages or collections, and cart value thresholds. Combine multiple rules to show the perfect message to the right customer at the right time.",
  },
  {
    question: "What triggers can I use to show popups?",
    answer:
      "We offer 5 smart trigger types: Exit Intent (captures leaving visitors), Scroll Depth (shows when visitors are engaged), Time on Page (after X seconds), Cart Value Threshold (upsell when cart hits a certain amount), and Page Load with delay. You can also combine triggers for even more precision.",
  },
  {
    question: "How do discount codes work?",
    answer:
      "Revenue Boost can automatically generate unique or shared discount codes for your campaigns. Codes can auto-apply to the cart (no copy/paste needed), have expiration dates and usage limits, and work seamlessly with Shopify's native discount system. Perfect for spin-to-win wheels, flash sales, or email signup incentives.",
  },
  {
    question: "Does Revenue Boost have A/B testing?",
    answer:
      "Yes! Our Growth and Pro plans include built-in A/B testing. You can test up to 4 variants per experiment, and we'll calculate statistical significance automatically. Track impressions, conversions, and actual revenue per variant to know exactly what works. Stop guessing, start testing.",
  },
  {
    question: "Can I track revenue generated by popups?",
    answer:
      "Absolutely. Revenue Boost tracks actual revenue generated by each popup campaign, not just conversions. See exactly how much money each campaign makes, calculate real ROI, and make data-driven decisions about which popups to keep running.",
  },
  {
    question: "Can I customize the design to match my brand?",
    answer:
      "Yes! Every template is fully customizable. You can change colors, fonts, images, text, timing, and animations. You can also use custom CSS on our Pro plan for complete control.",
  },
  {
    question: "Do you offer a free plan?",
    answer:
      "Yes, we offer a generous free plan with up to 3,000 popup views per month. This lets you test core features before upgrading. Paid plans also include a 14-day free trial.",
  },
  {
    question: "Is Revenue Boost GDPR compliant?",
    answer:
      "Yes, Revenue Boost is fully GDPR compliant. We don't store any customer data on our servers, and all data collection is handled through your Shopify store. We also provide consent collection features.",
  },
  {
    question: "Can I use Revenue Boost with my existing email marketing tools?",
    answer:
      "Yes! Revenue Boost works seamlessly with Klaviyo, Mailchimp, Omnisend, ActiveCampaign, and any email platform that syncs with Shopify customers. When someone signs up through your popup, they're added as a Shopify customer with marketing consent and campaign tags — your email platform picks them up automatically. No API keys or extra setup required.",
  },
]

// Generate FAQ structured data for SEO
const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqs.map((faq) => ({
    "@type": "Question",
    name: faq.question,
    acceptedAnswer: {
      "@type": "Answer",
      text: faq.answer,
    },
  })),
}

export function FaqSection() {
  return (
    <section id="faq" className="px-4 py-20 md:py-32">
      {/* FAQ Schema for SEO */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(faqSchema),
        }}
      />

      <div className="container mx-auto">
        <div className="mx-auto mb-16 max-w-2xl text-center">
          <h2 className="mb-4 text-3xl font-bold text-foreground md:text-4xl">Frequently Asked Questions</h2>
          <p className="text-lg text-muted-foreground">Got questions? We've got answers.</p>
        </div>

        <div className="mx-auto max-w-3xl">
          <Accordion type="single" collapsible className="w-full">
            {faqs.map((faq, index) => (
              <AccordionItem key={index} value={`item-${index}`}>
                <AccordionTrigger className="text-left text-foreground hover:text-primary">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground">{faq.answer}</AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </div>
    </section>
  )
}
